---
title: "Project Introduction"
description: |
  Objectives and Significance of the Project
site: distill::distill_website


---

### *MadCrime* 

This is the website for Stat 479 Data Visualization Final Project (Group 2) Department of Statistics, UW-Madison.


### Introduction

In fact, the world has gone through a very difficult time in 2019 and 2020. The global pandemic and the quarantine order has limited individuals’ freedom in a variety of ways. Additionally, all kinds of protests served as catalysts which ultimately contributed to the rise of the crime rate.

Data visualization in community crime analysis serves as an essential tool to protect residents’ safety. Cities such as Chicago have developed crime maps to inform citizens about various crimes that have happened across time. For instance, Chicago Data Portal (https://data.cityofchicago.org) published useful interactive data visualization to identify crime type, time, region, race, etc., in Chicago. However, such an interactive visualization tool is not well-developed in Madison, Wisconsin. Therefore, our group aims to create a tool that can help Madison residents learn more about community crime in 2019 and 2020.

The optimal goal for our team is to integrate the map of Madison with visual techniques to construct an observable presentation of street safety, which can come in handy for residents to check street safety and for future researchers to analyze related topics such as the crime rates in Madison based on crime category, date, and zip codes.


### Code

* Observable Notebook
  1. Time Series [Heatmap](https://observablehq.com/@hchen549/heatmap)
  2. [Leaflet map](https://observablehq.com/@hchen549/leaflet-heatmap)
* R Markdown
  1. All the Rmd files can be accessed on [Github](https://github.com/hchen549/Stat479_FinalProject)

