---
title: "Visualization"
description: |
  An explanation of how to read or interact with each visualization 
# site: distill::distill_website
output:
  distill::distill_article:
    toc: true
    toc_float: true
    toc_collapsed: false
    self_contained: True

---

<div class="row" style="padding-top: 10px;">
<div class="col-sm-10">



## *Visualization*


</div>

</div>

```{r echo=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(tidyr)
library(leaflet)
library("robservable")
library(rgdal)
library("ggnetwork")
library("sf")
library(lubridate)
library(sp)
data <- read.csv("https://geog573spring2021.s3.amazonaws.com/original_dataset.csv")
```


```{r}
# robservable("@hchen549/final-project", include = c("viewof crimeCategory","viewof chosenDate", "crimePlot"),height = 800)
```



```{r echo=FALSE}
data$Occur_date <- format(as.Date(data$Occur_date, format = "%m/%d/%Y"), "%Y-%m-%d")
data$Occur_weekday <- weekdays(as.Date(data$Occur_date))
new_data <- data[, c(10,13,9,2,12,11,5,6,7,8)] # reoder columns
new_data<-new_data[-c(7,39,58,62), ]
new_data<-new_data[!grepl("1971|1973|1994|1997|2008|2011|2018", new_data$Occur_date),]
new_data$time<-format(strptime(new_data$time, "%I:%M %p"), format="%H:%M")

new_data<- new_data %>% 
  arrange(desc(Occur_date)) %>%
  filter(!is.na(lon)) %>%
  filter(!is.na(lat))

# new_data
geo_data = st_as_sf(new_data, coords = c("lon", "lat"),  crs = 4326)
# geo_data

# new_data

# write.csv(new_data, "new_data.csv")
```

```{r}
new_data$month<-month(as.Date(new_data$Occur_date, "%Y-%m-%d"))
new_data$year<-year(as.Date(new_data$Occur_date, "%Y-%m-%d"))

crime = new_data %>%
  group_by(month,year) %>%
  count(incident) 

crime_sum = crime %>%
  group_by(month,year) %>%
  summarise(sumcrime = sum(n)) %>%
  filter(year == "2019" |year == "2020")

#ggplot showing the change of number of crime in each month per year
ggplot(crime_sum) +
  geom_line(aes(x = as.factor(month), y = sumcrime, group =as.factor(year) ,col = as.factor(year))) +
  xlab("Month") +
  ylab("Number of Crime") +
  scale_colour_discrete( name="year")
```



## Crime Activity Heatmap

```{r, fig.width=6, fig.height= 4.5}
# robservable("@hchen549/heatmap", include = c("chart_2019") ,
#             input = list(
#     title = "COVID-19 deaths",
#     subtitle = "Cumulative number of COVID-19 deaths by country",
#     source = "Source : Johns Hopkins University"
#   ),height = 150, width = 1200)
# robservable("@hchen549/heatmap", include = c("chart_2020") ,height = 150, width = 1200)
# robservable("@hchen549/heatmap", include = c("chart_2021") ,height = 150, width = 1200)
```

```{r, fig.width=10, fig.height= 1.6}
robservable("@hchen549/heatmap", include = c("chart_2020") ,
            input = list(
    title = "COVID-19 deaths",
    subtitle = "Cumulative number of COVID-19 deaths by country",
    source = "Source : Johns Hopkins University"
  ))
robservable("@hchen549/heatmap", include = c("chart_2021") ,
            input = list(
    title = "COVID-19 deaths",
    subtitle = "Cumulative number of COVID-19 deaths by country",
    source = "Source : Johns Hopkins University"
  ))

```

### Explanation
### Conclusion



```{r echo=FALSE}
robbery = new_data %>%
  filter(incident == "Robbery")
disturbance = new_data %>%
  filter(incident == "Disturbance")
```

```{r echo=FALSE}
zip53714 <- rgdal::readOGR("https://geog573spring2021.s3.amazonaws.com/US_ZC_53714.geojson")

```


## Crime Distribution

```{r, l-body-outset}
robservable("@hchen549/leaflet", include = c("viewof crimeCategory", "viewof start_date", "viewof end_date", "crimeMap"), height = 800, width = 600)
```

### Explanation
### Conclusion


```{r}
m = leaflet() %>%
  addTiles() %>%
  #addProviderTiles(providers$Stamen.Watercolor) %>%
  addPolygons(data = zip53714, weight = 1) %>%
  addCircleMarkers(lng = robbery$lon, lat = robbery$lat, color = "red", radius = 0.5, group = "robbery") %>%
  addCircleMarkers(lng = disturbance$lon, lat = disturbance$lat, color = "blue", radius = 0.5, group = "disturbance") %>%
  addLayersControl(overlayGroups = c("robbery", "disturbance"),
                   options = layersControlOptions(collapsed = F)) %>%
  setView(lng = -89.23, lat =43.04, zoom = 10)
m
```

## Crime by zipcode

```{r}
zipfile = readOGR("./data/wi_zip.shp")

unique_zip = new_data %>%
  group_by(zip) %>%
  summarise(count = n()) %>%
  filter(!is.na(zip))

zipfile = subset(zipfile, is.element(zipfile$ZCTA5CE10, unique_zip$zip))

unique_zip = unique_zip[order(match(unique_zip$zip,zipfile$ZCTA5CE10)), ]

# zipfile

# order(match(unique_zip$zip,zipfile$ZCTA5CE10))
```



```{r}
pal <- colorQuantile("YlOrRd", domain=(unique_zip$count), n = 8)


leaflet() %>%
  addProviderTiles(providers$CartoDB.Positron)%>%
  addPolygons(data = zipfile, weight = 2,
              fillColor = pal(unique_zip$count) ,
              popup = paste("Region: ", unique_zip$zip, "<br>",
                            "Count: ", unique_zip$count, "<br>")) %>% 
             
  setView(lng = -89.23, lat =43.04, zoom = 10) %>%
  addLegend(values= unique_zip$count,pal=pal,title="Incidents")

  
```

```{r}
#finding out highest incidents
crime_order = crime %>%
  group_by(incident,year) %>%
  summarise(sum = sum(n)) %>%
  arrange(desc(sum))

#According to the result, Weapons Violation, Robbery, Residential Burglary, Traffic Incident, and Theft have the most number of crime in 2019 and 2020.

#subsetting highest incidents
data_2019 = new_data %>%
  filter(incident == "Weapons Violation" | incident == "Robbery" | incident == "Residential Burglary" | incident == "Traffic Incident" | incident == "Theft" ) %>%
  group_by (zip,year) %>%
  count(incident) %>%
  filter(year == "2019" | year == "2020") %>% 
  drop_na() 

#Stacked bar plot, facet by year
ggplot(data_2019,aes(x = as.factor(zip), y = n)) +
  geom_col(aes(fill = incident), width = 0.7)+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  xlab("Zip") +
  ylab("Number of Crime") +
  facet_grid(. ~ year) +
  theme(legend.position = "bottom")
  

```

### Explanation
### Conclusion


```{r}
# zipcode <- rgdal::readOGR("wi_wisconsin_zip_codes_geo.min.geojson")
# zipcode = subset(zipcode, is.element(zipcode@data$ZCTA5CE10, new_data$zip))
# zipcode
```













